CREATE DATABASE proyectoSQL;

-- Crear la tabla roles
CREATE TABLE roles (
    id_rol NUMBER NOT NULL,
    rol VARCHAR2(20) NOT NULL,
    CONSTRAINT pk_roles PRIMARY KEY (id_rol)
);

-- Crear la tabla usuario
CREATE TABLE usuario (
    id_usuario NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL, 
    nombre VARCHAR2(50) NOT NULL,
    primer_apellido VARCHAR2(50) NOT NULL,
    segundo_apellido VARCHAR2(50) NOT NULL,
    correo VARCHAR2(50) NOT NULL,
    tipo_suscripcion VARCHAR2(50) NOT NULL,
    id_rol NUMBER,
    password VARCHAR2(255),
    CONSTRAINT pk_usuario PRIMARY KEY (id_usuario),
    CONSTRAINT fk_usuario_rol FOREIGN KEY (id_rol) REFERENCES roles(id_rol)
);

-- Insertar datos en la tabla roles
INSERT INTO roles (id_rol, rol) VALUES (1, 'admin');
INSERT INTO roles (id_rol, rol) VALUES (2, 'user');

-- Crear la tabla detalles_usuario
CREATE TABLE detalles_usuario (
    id_detalle NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL, 
    fecha_nacimiento DATE,
    altura_persona FLOAT(10),
    peso_persona FLOAT(10),
    lesiones VARCHAR2(50),
    medicamentos VARCHAR2(100),
    embarazo VARCHAR2(50),
    cirugia VARCHAR2(200),
    objetivos CLOB,
    id_usuario NUMBER(3) NOT NULL,
    CONSTRAINT pk_detalles_usuario PRIMARY KEY (id_detalle),
    CONSTRAINT fk_detalles_usuario_usuario FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario)
);

-- Crear la tabla rutina
CREATE TABLE rutina (
    id_rutina NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre_rutina VARCHAR2(50) NOT NULL,
    dia_rutina VARCHAR2(30) NOT NULL,
    id_usuario NUMBER(3),
    CONSTRAINT pk_rutina PRIMARY KEY (id_rutina),
    CONSTRAINT fk_rutina_usuario FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario)
);

-- Crear la tabla ejercicio
CREATE TABLE ejercicio (
    id_ejercicio NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre_ejercicio VARCHAR2(100) NOT NULL,
    setsE VARCHAR2(30) NOT NULL,
    maquina VARCHAR2(50) NOT NULL,
    observaciones CLOB,
    id_rutina NUMBER(3),
    CONSTRAINT pk_ejercicio PRIMARY KEY (id_ejercicio),
    CONSTRAINT fk_ejercicio_rutina FOREIGN KEY (id_rutina) REFERENCES rutina(id_rutina)
);

-- Crear la tabla notaMes
CREATE TABLE notaMes (
    id_check NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nota_mensual CLOB,
    id_foto NUMBER,
    CONSTRAINT pk_notaMes PRIMARY KEY (id_check),
    CONSTRAINT fk_notaMes_usuario FOREIGN KEY (id_foto) REFERENCES fotos(id_foto)
);

-- Crear la tabla fotos
CREATE TABLE fotos (
    id_foto NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    mes VARCHAR2(50) NOT NULL,
    anno VARCHAR2(50) NOT NULL,
    ruta_foto VARCHAR2(250),                                 
    id_usuario NUMBER(11),
    CONSTRAINT pk_fotos PRIMARY KEY (id_foto),
    CONSTRAINT fk_fotos_usuario FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario)
);

-- Crear la tabla pagos
CREATE TABLE pagos(
    id_pago NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    monto NUMBER(10),
    dia_pago VARCHAR2(20),
    estado VARCHAR2(20),
    id_usuario NUMBER,
    CONSTRAINT fk_pagos_usuario FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario)
);
